// <auto-generated />
namespace FlagChecker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration6changesharescountrytobytesinsteadofobject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration6changesharescountrytobytesinsteadofobject));
        
        string IMigrationMetadata.Id
        {
            get { return "201711121828277_Migration6 - change share's country to bytes instead of object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
