// <auto-generated />
namespace FlagChecker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration3addAreacolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration3addAreacolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201707252041590_Migration3 - add Area column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
