// <auto-generated />
namespace FlagChecker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration4AddENandPLnamingforcountries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration4AddENandPLnamingforcountries));
        
        string IMigrationMetadata.Id
        {
            get { return "201711112227534_Migration4- Add EN and PL naming for countries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
