//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlagChecker.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Additional_Details {
            get {
                return ResourceManager.GetString("Additional_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Additional_Flags {
            get {
                return ResourceManager.GetString("Additional_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Additional_Share {
            get {
                return ResourceManager.GetString("Additional_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Additional_Stats {
            get {
                return ResourceManager.GetString("Additional_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chosen countries.
        /// </summary>
        public static string Main_ChosenCountries {
            get {
                return ResourceManager.GetString("Main_ChosenCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to countries.
        /// </summary>
        public static string Main_Countries {
            get {
                return ResourceManager.GetString("Main_Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english.
        /// </summary>
        public static string Main_CurrentLanguage {
            get {
                return ResourceManager.GetString("Main_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string Main_Language {
            get {
                return ResourceManager.GetString("Main_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to summary.
        /// </summary>
        public static string Main_Summary {
            get {
                return ResourceManager.GetString("Main_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize.
        /// </summary>
        public static string Main_SumUp {
            get {
                return ResourceManager.GetString("Main_SumUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa.
        /// </summary>
        public static string Stats_Africa {
            get {
                return ResourceManager.GetString("Stats_Africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of all countries.
        /// </summary>
        public static string Stats_AllCountries {
            get {
                return ResourceManager.GetString("Stats_AllCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to world surface.
        /// </summary>
        public static string Stats_Area {
            get {
                return ResourceManager.GetString("Stats_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia.
        /// </summary>
        public static string Stats_Asia {
            get {
                return ResourceManager.GetString("Stats_Asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia and Oceania.
        /// </summary>
        public static string Stats_Australia {
            get {
                return ResourceManager.GetString("Stats_Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to countries.
        /// </summary>
        public static string Stats_Countries {
            get {
                return ResourceManager.GetString("Stats_Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string Stats_Europe {
            get {
                return ResourceManager.GetString("Stats_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate iImages.
        /// </summary>
        public static string Stats_GenerateImages {
            get {
                return ResourceManager.GetString("Stats_GenerateImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km².
        /// </summary>
        public static string Stats_Km2 {
            get {
                return ResourceManager.GetString("Stats_Km2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        public static string Stats_NAmerica {
            get {
                return ResourceManager.GetString("Stats_NAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open generator.
        /// </summary>
        public static string Stats_OpenGenerator {
            get {
                return ResourceManager.GetString("Stats_OpenGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South America.
        /// </summary>
        public static string Stats_SAmerica {
            get {
                return ResourceManager.GetString("Stats_SAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share link.
        /// </summary>
        public static string Stats_ShareLink {
            get {
                return ResourceManager.GetString("Stats_ShareLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Stats_TextArea {
            get {
                return ResourceManager.GetString("Stats_TextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Stats_TextCode {
            get {
                return ResourceManager.GetString("Stats_TextCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent.
        /// </summary>
        public static string Stats_TextContinent {
            get {
                return ResourceManager.GetString("Stats_TextContinent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Stats_TextName {
            get {
                return ResourceManager.GetString("Stats_TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to countries visited.
        /// </summary>
        public static string Title_CountriesVisited {
            get {
                return ResourceManager.GetString("Title_CountriesVisited", resourceCulture);
            }
        }
    }
}
